
STATUS_TYPE_ACTIVE = 'A'
STATUS_TYPE_INACTIVE = 'I'

STATUS_CHOICES = (
    (STATUS_TYPE_ACTIVE, 'Active'),
    (STATUS_TYPE_ACTIVE, 'Inactive'),
)

INSTITUTE_TYPE_SYSTEM = 'S'
INSTITUTE_TYPE_APPLICATION = 'A'

INSTITUTE_TYPE_CHOICES = (
		(INSTITUTE_TYPE_SYSTEM, 'System'),
		(INSTITUTE_TYPE_APPLICATION, 'Application'),
	)

NOTIFICATION_ACTIVE = 'A'
NOTIFICATION_FAILED = 'F'
NOTIFICATION_PENDING = 'P'

NOTIFICATION_CHOICES = (
	(NOTIFICATION_ACTIVE, 'Active')
	(NOTIFICATION_FAILED, 'Failed')
	(NOTIFICATION_PENDING, 'Pending')
)